# Generated by Django 5.2.5 on 2025-08-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=200)),
            ],
        ),
    ]
